# Generated by Django 2.2.5 on 2019-10-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='paramString',
            field=models.TextField(default='{}'),
        ),
    ]
