# Generated by Django 2.2.5 on 2019-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0002_dialog_paramstring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='paramString',
            new_name='graphJsonString',
        ),
    ]
