# Generated by Django 2.2.5 on 2019-10-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0006_auto_20191030_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='predicate',
            field=models.TextField(default=''),
        ),
    ]
