# Generated by Django 2.2.5 on 2019-11-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0007_dialog_predicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='target',
            field=models.TextField(default=''),
        ),
    ]
